language: node_js

node_js:
  - "0.10"

before_install:
  - npm install -g npm@'>=2.0.0'

install:
  - npm install -g codeclimate-test-reporter
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
